require('settings.general')
require('settings.telescope')
require('settings.cmp')
require('settings.catppuccin')
require('settings.oil')
require('settings.treesitter')
require('settings.lsp')
require('settings.autopairs')
